2023-01-24 16:06:58,699 - [INFO] - undetected_chromedriver.patcher - patch_exe(231) - patching driver executable C:\Users\zaitsev_ad\appdata\roaming\undetected_chromedriver\e51ef1044b910882_chromedriver.exe
2023-01-24 16:07:11,613 - [INFO] - undetected_chromedriver.patcher - patch_exe(231) - patching driver executable C:\Users\zaitsev_ad\appdata\roaming\undetected_chromedriver\a4293a65e1ae8fef_chromedriver.exe
2023-01-24 16:07:15,468 - [INFO] - main_ERKNM - __init__(59) - Начало авторизации
2023-01-24 16:07:25,487 - [INFO] - main_ERKNM - autorize(161) - Autorization successfull completed!
2023-01-24 16:07:28,202 - [INFO] - ERKNM_http.py - get_all_pm_for_a_year(249) - сбор данных завершен, записываем для сохранения в json
2023-01-24 16:07:28,236 - [INFO] - ERKNM_http.py - get_all_pm_for_a_year(253) - Запись в json завершена, заносим в базу данных
2023-01-24 16:07:58,597 - [INFO] - undetected_chromedriver.patcher - patch_exe(231) - patching driver executable C:\Users\zaitsev_ad\appdata\roaming\undetected_chromedriver\69d8a7a4f4e3439a_chromedriver.exe
2023-01-24 16:08:01,270 - [INFO] - main_ERKNM - __init__(59) - Начало авторизации
2023-01-24 16:08:10,520 - [INFO] - main_ERKNM - autorize(161) - Autorization successfull completed!
2023-01-24 16:08:13,354 - [INFO] - ERKNM_http.py - get_all_pm_for_a_year(249) - сбор данных завершен, записываем для сохранения в json
2023-01-24 16:08:13,389 - [INFO] - ERKNM_http.py - get_all_pm_for_a_year(253) - Запись в json завершена, заносим в базу данных
2023-01-24 16:35:27,713 - [INFO] - undetected_chromedriver.patcher - patch_exe(231) - patching driver executable C:\Users\zaitsev_ad\appdata\roaming\undetected_chromedriver\54fccf91fe3fba8b_chromedriver.exe
2023-01-24 16:35:30,387 - [INFO] - main_ERKNM - __init__(59) - Начало авторизации
2023-01-24 16:35:39,760 - [INFO] - main_ERKNM - autorize(161) - Autorization successfull completed!
2023-01-24 16:35:42,620 - [INFO] - ERKNM_http.py - get_all_pm_for_a_year(249) - сбор данных завершен, записываем для сохранения в json
2023-01-24 16:35:42,659 - [INFO] - ERKNM_http.py - get_all_pm_for_a_year(253) - Запись в json завершена, заносим в базу данных
2023-01-24 16:38:16,734 - [INFO] - undetected_chromedriver.patcher - patch_exe(231) - patching driver executable C:\Users\zaitsev_ad\appdata\roaming\undetected_chromedriver\be66a0c35716f0f2_chromedriver.exe
2023-01-24 16:38:19,237 - [INFO] - main_ERKNM - __init__(59) - Начало авторизации
2023-01-24 16:38:28,725 - [INFO] - main_ERKNM - autorize(161) - Autorization successfull completed!
2023-01-24 16:38:31,580 - [INFO] - ERKNM_http.py - get_all_pm_for_a_year(250) - сбор данных завершен, записываем для сохранения в json
2023-01-24 16:38:31,615 - [INFO] - ERKNM_http.py - get_all_pm_for_a_year(254) - Запись в json завершена, заносим в базу данных
2023-01-24 16:43:02,551 - [INFO] - undetected_chromedriver.patcher - patch_exe(231) - patching driver executable C:\Users\zaitsev_ad\appdata\roaming\undetected_chromedriver\8e16f04f1c6c8784_chromedriver.exe
2023-01-24 16:43:05,185 - [INFO] - main_ERKNM - __init__(59) - Начало авторизации
2023-01-24 16:43:14,211 - [INFO] - main_ERKNM - autorize(161) - Autorization successfull completed!
2023-01-24 16:43:16,950 - [INFO] - ERKNM_http.py - get_all_pm_for_a_year(251) - сбор данных завершен, записываем для сохранения в json
2023-01-24 16:43:16,985 - [INFO] - ERKNM_http.py - get_all_pm_for_a_year(255) - Запись в json завершена, заносим в базу данных
2023-01-24 16:44:00,439 - [INFO] - undetected_chromedriver.patcher - patch_exe(231) - patching driver executable C:\Users\zaitsev_ad\appdata\roaming\undetected_chromedriver\8eafd83537a32e4e_chromedriver.exe
2023-01-24 16:44:03,057 - [INFO] - main_ERKNM - __init__(59) - Начало авторизации
2023-01-24 16:44:12,813 - [INFO] - main_ERKNM - autorize(161) - Autorization successfull completed!
2023-01-24 16:45:19,855 - [INFO] - ERKNM_http.py - get_all_pm_for_a_year(251) - сбор данных завершен, записываем для сохранения в json
2023-01-24 16:45:33,688 - [INFO] - ERKNM_http.py - get_all_pm_for_a_year(255) - Запись в json завершена, заносим в базу данных
2023-01-24 16:47:02,503 - [INFO] - undetected_chromedriver.patcher - patch_exe(231) - patching driver executable C:\Users\zaitsev_ad\appdata\roaming\undetected_chromedriver\1bccc390a229af35_chromedriver.exe
2023-01-24 16:47:43,900 - [INFO] - undetected_chromedriver.patcher - patch_exe(231) - patching driver executable C:\Users\zaitsev_ad\appdata\roaming\undetected_chromedriver\88f847bccd976ea8_chromedriver.exe
2023-01-24 16:47:46,543 - [INFO] - main_ERKNM - __init__(59) - Начало авторизации
2023-01-24 16:47:56,003 - [INFO] - main_ERKNM - autorize(161) - Autorization successfull completed!
2023-01-24 16:48:11,288 - [INFO] - ERKNM_http.py - get_all_pm_for_a_year(251) - сбор данных завершен, записываем для сохранения в json
2023-01-24 16:48:14,993 - [INFO] - ERKNM_http.py - get_all_pm_for_a_year(255) - Запись в json завершена, заносим в базу данных
2023-01-24 16:48:15,210 - [ERROR] - sql.py - ultra_create_handler(115) - не получилось найти теруправление с параметром enter_terr_upr:
Traceback (most recent call last):
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\sql.py", line 112, in ultra_create_handler
    cursor.execute(f"""SELECT id FROM knd_terr_upravlenie WHERE controllingOrganizationId="{controllingOrganizationId}";""")
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
pymysql.err.InterfaceError: (0, '')
2023-01-24 16:48:15,223 - [INFO] - sql.py - ultra_create_handler(116) - {'actCreateDate': [], 'actCreateDateEn': [], 'addresses': ['420124, РЕСПУБЛИКА, ТАТАРСТАН, ГОРОД, КАЗАНЬ, УЛИЦА, АБДУЛЛЫ БИЧУРИНА, ДОМ 22/26, 160000010005299'], 'admLevelId': 50001, 'appealed': False, 'approveDocOrderDate': None, 'approveDocOrderNum': None, 'approveDocRequestDate': None, 'approveDocRequestNum': None, 'approveDocs': [], 'approveRequired': False, 'approved': None, 'approvedErknm': None, 'chlistCount': 0, 'chlistFilledCount': 0, 'chlistFillingIndicationTypeId': [], 'collaboratingOrganizations': [], 'collaboratingOrganizationsIds': [], 'comment': None, 'controllingOrganization': 'Управление Роспотребнадзора по Республике Татарстан', 'controllingOrganizationId': 10001021215, 'createPlanDate': None, 'createPlanDateLong': None, 'createdByErpDb': False, 'createdById': 147717, 'dataNotEqualEGRUL': False, 'dataSetNotInTime': True, 'deleted': False, 'directDurationDays': None, 'disapprove': False, 'district': None, 'districtId': None, 'durationDays': None, 'durationHours': None, 'erknmActViolationIds': [], 'erknmResultKindDecisionIds': [], 'erpId': '16220041000101521498', 'events': [], 'federalLaw': '248', 'federalLawId': 3, 'fullFieldViolationKnm': False, 'hasViolations': False, 'id': 11593623, 'inn': '1657029174', 'inspectorFullName': ['Ибрагимова Айгуль Равилевна'], 'isFromSmev': False, 'isHasApproveDocs': False, 'isHasCollaboratingOrganization': False, 'isHasRequirements': False, 'isHasViolationTerm': False, 'isPm': True, 'kind': 'Профилактический визит', 'knmAnnulled': False, 'knmRejected': False, 'knmType': None, 'knmTypeId': None, 'legalBasisDocName': [], 'links': [], 'mspCategory': [], 'noPunishment': False, 'notifyLate': False, 'objectsKind': ['организации отдыха детей и их оздоровления, в том числе лагеря с дневным пребыванием'], 'objectsSubKind': [], 'objectsType': [], 'ogrn': '1021603143770', 'oldKnm': None, 'oldPlan': None, 'orderDone': False, 'organizationName': 'ГОСУДАРСТВЕННОЕ АВТОНОМНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧРЕЖДЕНИЕ "ПОЛИЛИНГВАЛЬНЫЙ КОМПЛЕКС "АДЫМНАР-ПУТЬ К ЗНАНИЯМ И СОГЛАСИЮ" Г.КАЗАНИ', 'organizationsInn': ['1657029174'], 'organizationsName': ['ГОСУДАРСТВЕННОЕ АВТОНОМНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧРЕЖДЕНИЕ "ПОЛИЛИНГВАЛЬНЫЙ КОМПЛЕКС "АДЫМНАР-ПУТЬ К ЗНАНИЯМ И СОГЛАСИЮ" Г.КАЗАНИ'], 'organizationsOgrn': ['1021603143770'], 'planId': None, 'prosecutorOrganization': None, 'prosecutorOrganizationId': None, 'publishedStatus': 'PUBLISHED', 'reasons': [303], 'reasonsList': [], 'recEmptyOrLate': False, 'regDateEgrul': None, 'regDateEgrulEn': None, 'regLate': False, 'regTypes': [], 'requirements': 0, 'requirementsList': [], 'resolved': False, 'resultEmpty': True, 'resultEmptyOrLate': False, 'resultInfoTypeCodes': [], 'resultViolationKnm': False, 'riskCategory': ['-'], 'riskCategoryAndDangerClass': [], 'sezRegistryExists': False, 'signed': True, 'smevInfoType': None, 'smevMessageType': None, 'smevReceivedAt': None, 'smevReceivedAtEn': None, 'smevReceivedAtMonth': None, 'smevReceivedAtYear': None, 'spvRegistryExists': False, 'startDate': '05.01.2022', 'startDateEn': '2022-01-05', 'status': 'Отказ в проведении', 'statusEgrul': '', 'statusId': 22, 'stopDate': '05.01.2022', 'stopDateEn': '2022-01-05', 'subjectTypeId': 0, 'supervisionType': 'Федеральный государственный санитарно-эпидемиологический контроль (надзор)', 'supervisionTypeId': 4, 'torRegistryExists': False, 'updatePlanDate': None, 'updatePlanDateLong': None, 'version': 'ERKNM', 'violationLawsuitTypeCodes': [], 'violationTypeCodes': [], 'year': 2022}
2023-01-24 16:48:15,272 - [WARNING] - urllib3.connectionpool - _put_conn(305) - Connection pool is full, discarding connection: localhost. Connection pool size: 1
2023-01-24 16:48:15,272 - [ERROR] - sql.py - ultra_create_handler(115) - не получилось найти теруправление с параметром enter_terr_upr:
Traceback (most recent call last):
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\sql.py", line 112, in ultra_create_handler
    cursor.execute(f"""SELECT id FROM knd_terr_upravlenie WHERE controllingOrganizationId="{controllingOrganizationId}";""")
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
pymysql.err.InterfaceError: (0, '')
2023-01-24 16:48:15,273 - [INFO] - sql.py - ultra_create_handler(116) - {'actCreateDate': [], 'actCreateDateEn': [], 'addresses': ['656063, КРАЙ АЛТАЙСКИЙ, ГОРОД БАРНАУЛ, ПРОСПЕКТ КОСМОНАВТОВ, ДОМ 63, 22, 220000010000327'], 'admLevelId': 50001, 'appealed': False, 'approveDocOrderDate': None, 'approveDocOrderNum': None, 'approveDocRequestDate': None, 'approveDocRequestNum': None, 'approveDocs': [], 'approveRequired': False, 'approved': None, 'approvedErknm': None, 'chlistCount': 0, 'chlistFilledCount': 0, 'chlistFillingIndicationTypeId': [], 'collaboratingOrganizations': [], 'collaboratingOrganizationsIds': [], 'comment': None, 'controllingOrganization': 'Управление Роспотребнадзора по Алтайскомй краю', 'controllingOrganizationId': 10001013239, 'createPlanDate': None, 'createPlanDateLong': None, 'createdByErpDb': False, 'createdById': 169748, 'dataNotEqualEGRUL': False, 'dataSetNotInTime': True, 'deleted': False, 'directDurationDays': None, 'disapprove': False, 'district': None, 'districtId': None, 'durationDays': None, 'durationHours': None, 'erknmActViolationIds': [], 'erknmResultKindDecisionIds': [], 'erpId': '22220041000103560084', 'events': [], 'federalLaw': '248', 'federalLawId': 3, 'fullFieldViolationKnm': False, 'hasViolations': False, 'id': 13632201, 'inn': '2223033980', 'inspectorFullName': ['Вяткина Ольга Павловна'], 'isFromSmev': False, 'isHasApproveDocs': False, 'isHasCollaboratingOrganization': False, 'isHasRequirements': False, 'isHasViolationTerm': False, 'isPm': True, 'kind': 'Объявление предостережения', 'knmAnnulled': False, 'knmRejected': False, 'knmType': None, 'knmTypeId': None, 'legalBasisDocName': [], 'links': [], 'mspCategory': [], 'noPunishment': False, 'notifyLate': False, 'objectsKind': ['молоко, молочные продукты'], 'objectsSubKind': [], 'objectsType': [], 'ogrn': '1022201381696', 'oldKnm': None, 'oldPlan': None, 'orderDone': False, 'organizationName': 'АКЦИОНЕРНОЕ ОБЩЕСТВО  "БАРНАУЛЬСКИЙ МОЛОЧНЫЙ КОМБИНАТ "', 'organizationsInn': ['2223033980'], 'organizationsName': ['АКЦИОНЕРНОЕ ОБЩЕСТВО  "БАРНАУЛЬСКИЙ МОЛОЧНЫЙ КОМБИНАТ "'], 'organizationsOgrn': ['1022201381696'], 'planId': None, 'prosecutorOrganization': None, 'prosecutorOrganizationId': None, 'publishedStatus': 'PUBLISHED', 'reasons': [301], 'reasonsList': [], 'recEmptyOrLate': False, 'regDateEgrul': None, 'regDateEgrulEn': None, 'regLate': False, 'regTypes': [], 'requirements': 0, 'requirementsList': [], 'resolved': False, 'resultEmpty': True, 'resultEmptyOrLate': False, 'resultInfoTypeCodes': [], 'resultViolationKnm': False, 'riskCategory': ['-'], 'riskCategoryAndDangerClass': [], 'sezRegistryExists': False, 'signed': True, 'smevInfoType': None, 'smevMessageType': None, 'smevReceivedAt': None, 'smevReceivedAtEn': None, 'smevReceivedAtMonth': None, 'smevReceivedAtYear': None, 'spvRegistryExists': False, 'startDate': '01.01.2022', 'startDateEn': '2022-01-01', 'status': 'Предостережение объявлено', 'statusEgrul': '', 'statusId': 23, 'stopDate': '01.01.2022', 'stopDateEn': '2022-01-01', 'subjectTypeId': 0, 'supervisionType': 'Федеральный государственный санитарно-эпидемиологический контроль (надзор)', 'supervisionTypeId': 4, 'torRegistryExists': False, 'updatePlanDate': None, 'updatePlanDateLong': None, 'version': 'ERKNM', 'violationLawsuitTypeCodes': [], 'violationTypeCodes': [], 'year': 2022}
2023-01-24 16:55:44,360 - [INFO] - undetected_chromedriver.patcher - patch_exe(231) - patching driver executable C:\Users\zaitsev_ad\appdata\roaming\undetected_chromedriver\9febe71a6f69c518_chromedriver.exe
2023-01-24 16:55:47,085 - [INFO] - main_ERKNM - __init__(59) - Начало авторизации
2023-01-24 16:55:56,697 - [INFO] - main_ERKNM - autorize(161) - Autorization successfull completed!
2023-01-24 16:56:15,196 - [INFO] - ERKNM_http.py - get_all_pm_for_a_year(251) - сбор данных завершен, записываем для сохранения в json
2023-01-24 16:56:21,243 - [INFO] - ERKNM_http.py - get_all_pm_for_a_year(255) - Запись в json завершена, заносим в базу данных
2023-01-24 16:56:22,315 - [ERROR] - sql.py - ultra_create_handler(115) - не получилось найти теруправление с параметром enter_terr_upr:
Traceback (most recent call last):
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\sql.py", line 112, in ultra_create_handler
    cursor.execute(f"""SELECT id FROM knd_terr_upravlenie WHERE controllingOrganizationId="{controllingOrganizationId}";""")
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
pymysql.err.InterfaceError: (0, '')
2023-01-24 16:56:22,317 - [INFO] - sql.py - ultra_create_handler(116) - {'actCreateDate': [], 'actCreateDateEn': [], 'addresses': ['450068, РЕСПУБЛИКА, БАШКОРТОСТАН, УЛИЦА, Софьи Перовской, д. 54,'], 'admLevelId': 50001, 'appealed': False, 'approveDocOrderDate': None, 'approveDocOrderNum': None, 'approveDocRequestDate': None, 'approveDocRequestNum': None, 'approveDocs': [], 'approveRequired': False, 'approved': None, 'approvedErknm': None, 'chlistCount': 0, 'chlistFilledCount': 0, 'chlistFillingIndicationTypeId': [], 'collaboratingOrganizations': [], 'collaboratingOrganizationsIds': [], 'comment': None, 'controllingOrganization': 'Управление Роспотребнадзора по Республике Башкортостан', 'controllingOrganizationId': 10001024565, 'createPlanDate': None, 'createPlanDateLong': None, 'createdByErpDb': False, 'createdById': 173100, 'dataNotEqualEGRUL': False, 'dataSetNotInTime': False, 'deleted': False, 'directDurationDays': None, 'disapprove': False, 'district': None, 'districtId': None, 'durationDays': None, 'durationHours': None, 'erknmActViolationIds': [], 'erknmResultKindDecisionIds': [], 'erpId': '02230041000104658412', 'events': [], 'federalLaw': '248', 'federalLawId': 3, 'fullFieldViolationKnm': False, 'hasViolations': False, 'id': 14730529, 'inn': '027707152028', 'inspectorFullName': ['Шарафуллина Эльза Загитовна'], 'isFromSmev': False, 'isHasApproveDocs': False, 'isHasCollaboratingOrganization': False, 'isHasRequirements': False, 'isHasViolationTerm': False, 'isPm': True, 'kind': 'Объявление предостережения', 'knmAnnulled': False, 'knmRejected': False, 'knmType': None, 'knmTypeId': None, 'legalBasisDocName': [], 'links': [], 'mspCategory': [], 'noPunishment': False, 'notifyLate': False, 'objectsKind': [], 'objectsSubKind': [], 'objectsType': [], 'ogrn': '320028000008536', 'oldKnm': None, 'oldPlan': None, 'orderDone': False, 'organizationName': 'АГЛИУЛЛИНА ЕКАТЕРИНА АНДРЕЕВНА', 'organizationsInn': ['027707152028'], 'organizationsName': ['АГЛИУЛЛИНА ЕКАТЕРИНА АНДРЕЕВНА'], 'organizationsOgrn': ['320028000008536'], 'planId': None, 'prosecutorOrganization': None, 'prosecutorOrganizationId': None, 'publishedStatus': 'UNPUBLISHED', 'reasons': [301], 'reasonsList': [], 'recEmptyOrLate': False, 'regDateEgrul': None, 'regDateEgrulEn': None, 'regLate': False, 'regTypes': ['MSP'], 'requirements': 0, 'requirementsList': [], 'resolved': False, 'resultEmpty': True, 'resultEmptyOrLate': False, 'resultInfoTypeCodes': [], 'resultViolationKnm': False, 'riskCategory': [], 'riskCategoryAndDangerClass': [], 'sezRegistryExists': False, 'signed': False, 'smevInfoType': None, 'smevMessageType': None, 'smevReceivedAt': None, 'smevReceivedAtEn': None, 'smevReceivedAtMonth': None, 'smevReceivedAtYear': None, 'spvRegistryExists': False, 'startDate': '06.01.2023', 'startDateEn': '2023-01-06', 'status': 'В процессе заполнения', 'statusEgrul': '', 'statusId': 11, 'stopDate': None, 'stopDateEn': None, 'subjectTypeId': 0, 'supervisionType': 'Федеральный государственный санитарно-эпидемиологический контроль (надзор)', 'supervisionTypeId': 4, 'torRegistryExists': False, 'updatePlanDate': None, 'updatePlanDateLong': None, 'version': 'ERKNM', 'violationLawsuitTypeCodes': [], 'violationTypeCodes': [], 'year': 2023}
2023-01-24 16:58:51,188 - [INFO] - undetected_chromedriver.patcher - patch_exe(231) - patching driver executable C:\Users\zaitsev_ad\appdata\roaming\undetected_chromedriver\ab5d6378e616e908_chromedriver.exe
2023-01-24 16:58:54,017 - [INFO] - main_ERKNM - __init__(59) - Начало авторизации
2023-01-24 16:59:03,574 - [INFO] - main_ERKNM - autorize(161) - Autorization successfull completed!
2023-01-24 16:59:11,439 - [INFO] - ERKNM_http.py - get_all_pm_for_a_year(251) - сбор данных завершен, записываем для сохранения в json
2023-01-24 16:59:12,779 - [INFO] - ERKNM_http.py - get_all_pm_for_a_year(255) - Запись в json завершена, заносим в базу данных
2023-01-24 16:59:12,989 - [ERROR] - sql.py - ultra_create_handler(115) - не получилось найти теруправление с параметром enter_terr_upr:
Traceback (most recent call last):
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\sql.py", line 112, in ultra_create_handler
    cursor.execute(f"""SELECT id FROM knd_terr_upravlenie WHERE controllingOrganizationId="{controllingOrganizationId}";""")
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
pymysql.err.InterfaceError: (0, '')
2023-01-24 16:59:12,991 - [INFO] - sql.py - ultra_create_handler(116) - {'actCreateDate': [], 'actCreateDateEn': [], 'addresses': ['420124, РЕСПУБЛИКА, ТАТАРСТАН, ГОРОД, КАЗАНЬ, УЛИЦА, АБДУЛЛЫ БИЧУРИНА, ДОМ 22/26, 160000010005299'], 'admLevelId': 50001, 'appealed': False, 'approveDocOrderDate': None, 'approveDocOrderNum': None, 'approveDocRequestDate': None, 'approveDocRequestNum': None, 'approveDocs': [], 'approveRequired': False, 'approved': None, 'approvedErknm': None, 'chlistCount': 0, 'chlistFilledCount': 0, 'chlistFillingIndicationTypeId': [], 'collaboratingOrganizations': [], 'collaboratingOrganizationsIds': [], 'comment': None, 'controllingOrganization': 'Управление Роспотребнадзора по Республике Татарстан', 'controllingOrganizationId': 10001021215, 'createPlanDate': None, 'createPlanDateLong': None, 'createdByErpDb': False, 'createdById': 147717, 'dataNotEqualEGRUL': False, 'dataSetNotInTime': True, 'deleted': False, 'directDurationDays': None, 'disapprove': False, 'district': None, 'districtId': None, 'durationDays': None, 'durationHours': None, 'erknmActViolationIds': [], 'erknmResultKindDecisionIds': [], 'erpId': '16220041000101521498', 'events': [], 'federalLaw': '248', 'federalLawId': 3, 'fullFieldViolationKnm': False, 'hasViolations': False, 'id': 11593623, 'inn': '1657029174', 'inspectorFullName': ['Ибрагимова Айгуль Равилевна'], 'isFromSmev': False, 'isHasApproveDocs': False, 'isHasCollaboratingOrganization': False, 'isHasRequirements': False, 'isHasViolationTerm': False, 'isPm': True, 'kind': 'Профилактический визит', 'knmAnnulled': False, 'knmRejected': False, 'knmType': None, 'knmTypeId': None, 'legalBasisDocName': [], 'links': [], 'mspCategory': [], 'noPunishment': False, 'notifyLate': False, 'objectsKind': ['организации отдыха детей и их оздоровления, в том числе лагеря с дневным пребыванием'], 'objectsSubKind': [], 'objectsType': [], 'ogrn': '1021603143770', 'oldKnm': None, 'oldPlan': None, 'orderDone': False, 'organizationName': 'ГОСУДАРСТВЕННОЕ АВТОНОМНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧРЕЖДЕНИЕ "ПОЛИЛИНГВАЛЬНЫЙ КОМПЛЕКС "АДЫМНАР-ПУТЬ К ЗНАНИЯМ И СОГЛАСИЮ" Г.КАЗАНИ', 'organizationsInn': ['1657029174'], 'organizationsName': ['ГОСУДАРСТВЕННОЕ АВТОНОМНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧРЕЖДЕНИЕ "ПОЛИЛИНГВАЛЬНЫЙ КОМПЛЕКС "АДЫМНАР-ПУТЬ К ЗНАНИЯМ И СОГЛАСИЮ" Г.КАЗАНИ'], 'organizationsOgrn': ['1021603143770'], 'planId': None, 'prosecutorOrganization': None, 'prosecutorOrganizationId': None, 'publishedStatus': 'PUBLISHED', 'reasons': [303], 'reasonsList': [], 'recEmptyOrLate': False, 'regDateEgrul': None, 'regDateEgrulEn': None, 'regLate': False, 'regTypes': [], 'requirements': 0, 'requirementsList': [], 'resolved': False, 'resultEmpty': True, 'resultEmptyOrLate': False, 'resultInfoTypeCodes': [], 'resultViolationKnm': False, 'riskCategory': ['-'], 'riskCategoryAndDangerClass': [], 'sezRegistryExists': False, 'signed': True, 'smevInfoType': None, 'smevMessageType': None, 'smevReceivedAt': None, 'smevReceivedAtEn': None, 'smevReceivedAtMonth': None, 'smevReceivedAtYear': None, 'spvRegistryExists': False, 'startDate': '05.01.2022', 'startDateEn': '2022-01-05', 'status': 'Отказ в проведении', 'statusEgrul': '', 'statusId': 22, 'stopDate': '05.01.2022', 'stopDateEn': '2022-01-05', 'subjectTypeId': 0, 'supervisionType': 'Федеральный государственный санитарно-эпидемиологический контроль (надзор)', 'supervisionTypeId': 4, 'torRegistryExists': False, 'updatePlanDate': None, 'updatePlanDateLong': None, 'version': 'ERKNM', 'violationLawsuitTypeCodes': [], 'violationTypeCodes': [], 'year': 2022}
2023-01-24 17:03:55,489 - [INFO] - undetected_chromedriver.patcher - patch_exe(231) - patching driver executable C:\Users\zaitsev_ad\appdata\roaming\undetected_chromedriver\5f10ff45be4e97c5_chromedriver.exe
2023-01-24 17:03:58,112 - [INFO] - main_ERKNM - __init__(59) - Начало авторизации
2023-01-24 17:04:07,425 - [INFO] - main_ERKNM - autorize(161) - Autorization successfull completed!
2023-01-24 17:04:15,540 - [INFO] - ERKNM_http.py - get_all_pm_for_a_year(251) - сбор данных завершен, записываем для сохранения в json
2023-01-24 17:04:16,939 - [INFO] - ERKNM_http.py - get_all_pm_for_a_year(255) - Запись в json завершена, заносим в базу данных
2023-01-24 17:07:22,624 - [INFO] - undetected_chromedriver.patcher - patch_exe(231) - patching driver executable C:\Users\zaitsev_ad\appdata\roaming\undetected_chromedriver\00716a96ca3c70e3_chromedriver.exe
2023-01-24 17:07:25,178 - [INFO] - main_ERKNM - __init__(59) - Начало авторизации
2023-01-24 17:07:36,678 - [INFO] - main_ERKNM - autorize(161) - Autorization successfull completed!
2023-01-24 17:07:44,898 - [INFO] - ERKNM_http.py - get_all_pm_for_a_year(251) - сбор данных завершен, записываем для сохранения в json
2023-01-24 17:07:46,313 - [INFO] - ERKNM_http.py - get_all_pm_for_a_year(255) - Запись в json завершена, заносим в базу данных
2023-01-24 17:09:50,465 - [INFO] - undetected_chromedriver.patcher - patch_exe(231) - patching driver executable C:\Users\zaitsev_ad\appdata\roaming\undetected_chromedriver\3fc6f98fbb6b9c9a_chromedriver.exe
2023-01-24 17:09:52,996 - [INFO] - main_ERKNM - __init__(59) - Начало авторизации
2023-01-24 17:10:02,374 - [INFO] - main_ERKNM - autorize(161) - Autorization successfull completed!
2023-01-24 17:10:10,390 - [INFO] - ERKNM_http.py - get_all_pm_for_a_year(251) - сбор данных завершен, записываем для сохранения в json
2023-01-24 17:10:11,736 - [INFO] - ERKNM_http.py - get_all_pm_for_a_year(255) - Запись в json завершена, заносим в базу данных
2023-01-24 17:10:38,761 - [ERROR] - sql.py - ultra_create_handler(223) - не получилось внести субъект (не рейд):
Traceback (most recent call last):
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\sql.py", line 214, in ultra_create_handler
    cursor.execute(f"""INSERT INTO knd_subject(name, address, inn, ogrn, e_mail, district) VALUES (
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'ДЭЛИС РУСЬ"\', \'601123, ОБЛАСТЬ, ВЛАДИМИРСКАЯ, РАЙ\' at line 2')
2023-01-24 17:10:38,772 - [INFO] - sql.py - ultra_create_handler(224) - {'actCreateDate': [], 'actCreateDateEn': [], 'addresses': ['601123, ОБЛАСТЬ, ВЛАДИМИРСКАЯ, РАЙОН, ПЕТУШИНСКИЙ, ГОРОД, ПОКРОВ, УЛИЦА, ФРАНЦА ШТОЛЬВЕРКА, ДОМ 10, 330120030000031'], 'admLevelId': 50001, 'appealed': False, 'approveDocOrderDate': None, 'approveDocOrderNum': None, 'approveDocRequestDate': None, 'approveDocRequestNum': None, 'approveDocs': [], 'approveRequired': False, 'approved': None, 'approvedErknm': None, 'chlistCount': 0, 'chlistFilledCount': 0, 'chlistFillingIndicationTypeId': [], 'collaboratingOrganizations': [], 'collaboratingOrganizationsIds': [], 'comment': None, 'controllingOrganization': 'Управление Роспотребнадзора по Владимирской области', 'controllingOrganizationId': 10001023037, 'createPlanDate': None, 'createPlanDateLong': None, 'createdByErpDb': False, 'createdById': 162319, 'dataNotEqualEGRUL': False, 'dataSetNotInTime': True, 'deleted': False, 'directDurationDays': None, 'disapprove': False, 'district': None, 'districtId': None, 'durationDays': None, 'durationHours': None, 'erknmActViolationIds': [], 'erknmResultKindDecisionIds': [], 'erpId': '33220041000101558820', 'events': [], 'federalLaw': '248', 'federalLawId': 3, 'fullFieldViolationKnm': False, 'hasViolations': False, 'id': 11630945, 'inn': '3321020710', 'inspectorFullName': ['Перова Татьяна Сергеевна'], 'isFromSmev': False, 'isHasApproveDocs': False, 'isHasCollaboratingOrganization': False, 'isHasRequirements': False, 'isHasViolationTerm': False, 'isPm': True, 'kind': 'Объявление предостережения', 'knmAnnulled': False, 'knmRejected': False, 'knmType': None, 'knmTypeId': None, 'legalBasisDocName': [], 'links': [], 'mspCategory': [], 'noPunishment': False, 'notifyLate': False, 'objectsKind': ['кондитерские изделия'], 'objectsSubKind': [], 'objectsType': [], 'ogrn': '1053300622407', 'oldKnm': None, 'oldPlan': None, 'orderDone': False, 'organizationName': 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "МОН\'ДЭЛИС РУСЬ"', 'organizationsInn': ['3321020710'], 'organizationsName': ['ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "МОН\'ДЭЛИС РУСЬ"'], 'organizationsOgrn': ['1053300622407'], 'planId': None, 'prosecutorOrganization': None, 'prosecutorOrganizationId': None, 'publishedStatus': 'PUBLISHED', 'reasons': [301], 'reasonsList': [], 'recEmptyOrLate': False, 'regDateEgrul': None, 'regDateEgrulEn': None, 'regLate': False, 'regTypes': [], 'requirements': 0, 'requirementsList': [], 'resolved': False, 'resultEmpty': True, 'resultEmptyOrLate': False, 'resultInfoTypeCodes': [], 'resultViolationKnm': False, 'riskCategory': ['-'], 'riskCategoryAndDangerClass': [], 'sezRegistryExists': False, 'signed': True, 'smevInfoType': None, 'smevMessageType': None, 'smevReceivedAt': None, 'smevReceivedAtEn': None, 'smevReceivedAtMonth': None, 'smevReceivedAtYear': None, 'spvRegistryExists': False, 'startDate': '11.01.2022', 'startDateEn': '2022-01-11', 'status': 'Предостережение объявлено', 'statusEgrul': '', 'statusId': 23, 'stopDate': '24.01.2022', 'stopDateEn': '2022-01-24', 'subjectTypeId': 0, 'supervisionType': 'Федеральный государственный санитарно-эпидемиологический контроль (надзор)', 'supervisionTypeId': 4, 'torRegistryExists': False, 'updatePlanDate': None, 'updatePlanDateLong': None, 'version': 'ERKNM', 'violationLawsuitTypeCodes': [], 'violationTypeCodes': [], 'year': 2022}
2023-01-24 17:59:24,876 - [INFO] - undetected_chromedriver.patcher - patch_exe(231) - patching driver executable C:\Users\zaitsev_ad\appdata\roaming\undetected_chromedriver\3428d1a3017f0c57_chromedriver.exe
2023-01-24 17:59:27,440 - [INFO] - main_ERKNM - __init__(59) - Начало авторизации
2023-01-24 17:59:37,383 - [INFO] - main_ERKNM - autorize(161) - Autorization successfull completed!
2023-01-24 17:59:45,476 - [INFO] - ERKNM_http.py - get_all_pm_for_a_year(251) - сбор данных завершен, записываем для сохранения в json
2023-01-24 17:59:46,975 - [INFO] - ERKNM_http.py - get_all_pm_for_a_year(255) - Запись в json завершена, заносим в базу данных
2023-01-24 18:02:42,640 - [INFO] - undetected_chromedriver.patcher - patch_exe(231) - patching driver executable C:\Users\zaitsev_ad\appdata\roaming\undetected_chromedriver\f96c552251953590_chromedriver.exe
2023-01-24 18:02:45,780 - [INFO] - main_ERKNM - __init__(59) - Начало авторизации
2023-01-24 18:02:55,267 - [INFO] - main_ERKNM - autorize(161) - Autorization successfull completed!
2023-01-24 18:03:03,321 - [INFO] - ERKNM_http.py - get_all_pm_for_a_year(251) - сбор данных завершен, записываем для сохранения в json
2023-01-24 18:03:04,748 - [INFO] - ERKNM_http.py - get_all_pm_for_a_year(255) - Запись в json завершена, заносим в базу данных
2023-01-24 18:03:04,936 - [INFO] - direct_sql.py - multiple_inserts(142) - старт программы
2023-01-24 18:03:14,629 - [ERROR] - sql.py - ultra_create_handler(223) - не получилось внести субъект (не рейд):
Traceback (most recent call last):
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\sql.py", line 214, in ultra_create_handler
    cursor.execute(f"""INSERT INTO knd_subject(name, address, inn, ogrn, e_mail, district) VALUES (
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'ДЭЛИС РУСЬ"\', \'601123, ОБЛАСТЬ, ВЛАДИМИРСКАЯ, РАЙ\' at line 2')
2023-01-24 18:03:14,636 - [INFO] - sql.py - ultra_create_handler(224) - {'actCreateDate': [], 'actCreateDateEn': [], 'addresses': ['601123, ОБЛАСТЬ, ВЛАДИМИРСКАЯ, РАЙОН, ПЕТУШИНСКИЙ, ГОРОД, ПОКРОВ, УЛИЦА, ФРАНЦА ШТОЛЬВЕРКА, ДОМ 10, 330120030000031'], 'admLevelId': 50001, 'appealed': False, 'approveDocOrderDate': None, 'approveDocOrderNum': None, 'approveDocRequestDate': None, 'approveDocRequestNum': None, 'approveDocs': [], 'approveRequired': False, 'approved': None, 'approvedErknm': None, 'chlistCount': 0, 'chlistFilledCount': 0, 'chlistFillingIndicationTypeId': [], 'collaboratingOrganizations': [], 'collaboratingOrganizationsIds': [], 'comment': None, 'controllingOrganization': 'Управление Роспотребнадзора по Владимирской области', 'controllingOrganizationId': 10001023037, 'createPlanDate': None, 'createPlanDateLong': None, 'createdByErpDb': False, 'createdById': 162319, 'dataNotEqualEGRUL': False, 'dataSetNotInTime': True, 'deleted': False, 'directDurationDays': None, 'disapprove': False, 'district': None, 'districtId': None, 'durationDays': None, 'durationHours': None, 'erknmActViolationIds': [], 'erknmResultKindDecisionIds': [], 'erpId': '33220041000101558820', 'events': [], 'federalLaw': '248', 'federalLawId': 3, 'fullFieldViolationKnm': False, 'hasViolations': False, 'id': 11630945, 'inn': '3321020710', 'inspectorFullName': ['Перова Татьяна Сергеевна'], 'isFromSmev': False, 'isHasApproveDocs': False, 'isHasCollaboratingOrganization': False, 'isHasRequirements': False, 'isHasViolationTerm': False, 'isPm': True, 'kind': 'Объявление предостережения', 'knmAnnulled': False, 'knmRejected': False, 'knmType': None, 'knmTypeId': None, 'legalBasisDocName': [], 'links': [], 'mspCategory': [], 'noPunishment': False, 'notifyLate': False, 'objectsKind': [], 'objectsSubKind': [], 'objectsType': [], 'ogrn': '1053300622407', 'oldKnm': None, 'oldPlan': None, 'orderDone': False, 'organizationName': 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "МОН\'ДЭЛИС РУСЬ"', 'organizationsInn': ['3321020710'], 'organizationsName': ['ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "МОН\'ДЭЛИС РУСЬ"'], 'organizationsOgrn': ['1053300622407'], 'planId': None, 'prosecutorOrganization': None, 'prosecutorOrganizationId': None, 'publishedStatus': 'PUBLISHED', 'reasons': [301], 'reasonsList': [], 'recEmptyOrLate': False, 'regDateEgrul': None, 'regDateEgrulEn': None, 'regLate': False, 'regTypes': [], 'requirements': 0, 'requirementsList': [], 'resolved': False, 'resultEmpty': True, 'resultEmptyOrLate': False, 'resultInfoTypeCodes': [], 'resultViolationKnm': False, 'riskCategory': [], 'riskCategoryAndDangerClass': [], 'sezRegistryExists': False, 'signed': True, 'smevInfoType': None, 'smevMessageType': None, 'smevReceivedAt': None, 'smevReceivedAtEn': None, 'smevReceivedAtMonth': None, 'smevReceivedAtYear': None, 'spvRegistryExists': False, 'startDate': '11.01.2022', 'startDateEn': '2022-01-11', 'status': 'Предостережение объявлено', 'statusEgrul': '', 'statusId': 23, 'stopDate': '24.01.2022', 'stopDateEn': '2022-01-24', 'subjectTypeId': 0, 'supervisionType': 'Федеральный государственный санитарно-эпидемиологический контроль (надзор)', 'supervisionTypeId': 4, 'torRegistryExists': False, 'updatePlanDate': None, 'updatePlanDateLong': None, 'version': 'ERKNM', 'violationLawsuitTypeCodes': [], 'violationTypeCodes': [], 'year': 2022}
2023-01-24 18:04:04,470 - [INFO] - direct_sql.py - multiple_inserts(154) - Все проверки успешно занесены!
2023-01-24 18:06:29,499 - [INFO] - undetected_chromedriver.patcher - patch_exe(231) - patching driver executable C:\Users\zaitsev_ad\appdata\roaming\undetected_chromedriver\6aac0e1fb0a7f399_chromedriver.exe
2023-01-24 18:06:31,991 - [INFO] - main_ERKNM - __init__(59) - Начало авторизации
2023-01-24 18:06:43,024 - [WARNING] - urllib3.connectionpool - urlopen(812) - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017F21455AE0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение')': /session/a78bc0b3c2ee6c3047dabb228b0bbbfb
2023-01-24 18:06:47,192 - [WARNING] - urllib3.connectionpool - urlopen(812) - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017F1D9C9300>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение')': /session/a78bc0b3c2ee6c3047dabb228b0bbbfb
2023-01-24 18:06:51,252 - [WARNING] - urllib3.connectionpool - urlopen(812) - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017F2138E5C0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение')': /session/a78bc0b3c2ee6c3047dabb228b0bbbfb
2023-01-24 18:08:07,970 - [INFO] - undetected_chromedriver.patcher - patch_exe(231) - patching driver executable C:\Users\zaitsev_ad\appdata\roaming\undetected_chromedriver\3cc7604e470c90c1_chromedriver.exe
2023-01-24 18:08:10,681 - [INFO] - main_ERKNM - __init__(59) - Начало авторизации
2023-01-24 18:08:20,633 - [INFO] - main_ERKNM - autorize(161) - Autorization successfull completed!
2023-01-24 18:08:28,418 - [INFO] - ERKNM_http.py - get_all_pm_for_a_year(251) - сбор данных завершен, записываем для сохранения в json
2023-01-24 18:08:29,837 - [INFO] - ERKNM_http.py - get_all_pm_for_a_year(255) - Запись в json завершена, заносим в базу данных
2023-01-24 18:08:30,002 - [INFO] - direct_sql.py - multiple_inserts(142) - старт программы
2023-01-24 18:08:38,992 - [ERROR] - sql.py - ultra_create_handler(223) - не получилось внести субъект (не рейд):
Traceback (most recent call last):
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\sql.py", line 214, in ultra_create_handler
    cursor.execute(f"""INSERT INTO knd_subject(name, address, inn, ogrn, e_mail, district) VALUES (
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'ДЭЛИС РУСЬ"\', \'601123, ОБЛАСТЬ, ВЛАДИМИРСКАЯ, РАЙ\' at line 2')
2023-01-24 18:08:38,996 - [INFO] - sql.py - ultra_create_handler(224) - {'actCreateDate': [], 'actCreateDateEn': [], 'addresses': ['601123, ОБЛАСТЬ, ВЛАДИМИРСКАЯ, РАЙОН, ПЕТУШИНСКИЙ, ГОРОД, ПОКРОВ, УЛИЦА, ФРАНЦА ШТОЛЬВЕРКА, ДОМ 10, 330120030000031'], 'admLevelId': 50001, 'appealed': False, 'approveDocOrderDate': None, 'approveDocOrderNum': None, 'approveDocRequestDate': None, 'approveDocRequestNum': None, 'approveDocs': [], 'approveRequired': False, 'approved': None, 'approvedErknm': None, 'chlistCount': 0, 'chlistFilledCount': 0, 'chlistFillingIndicationTypeId': [], 'collaboratingOrganizations': [], 'collaboratingOrganizationsIds': [], 'comment': None, 'controllingOrganization': 'Управление Роспотребнадзора по Владимирской области', 'controllingOrganizationId': 10001023037, 'createPlanDate': None, 'createPlanDateLong': None, 'createdByErpDb': False, 'createdById': 162319, 'dataNotEqualEGRUL': False, 'dataSetNotInTime': True, 'deleted': False, 'directDurationDays': None, 'disapprove': False, 'district': None, 'districtId': None, 'durationDays': None, 'durationHours': None, 'erknmActViolationIds': [], 'erknmResultKindDecisionIds': [], 'erpId': '33220041000101558820', 'events': [], 'federalLaw': '248', 'federalLawId': 3, 'fullFieldViolationKnm': False, 'hasViolations': False, 'id': 11630945, 'inn': '3321020710', 'inspectorFullName': ['Перова Татьяна Сергеевна'], 'isFromSmev': False, 'isHasApproveDocs': False, 'isHasCollaboratingOrganization': False, 'isHasRequirements': False, 'isHasViolationTerm': False, 'isPm': True, 'kind': 'Объявление предостережения', 'knmAnnulled': False, 'knmRejected': False, 'knmType': None, 'knmTypeId': None, 'legalBasisDocName': [], 'links': [], 'mspCategory': [], 'noPunishment': False, 'notifyLate': False, 'objectsKind': [], 'objectsSubKind': [], 'objectsType': [], 'ogrn': '1053300622407', 'oldKnm': None, 'oldPlan': None, 'orderDone': False, 'organizationName': 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "МОН\'ДЭЛИС РУСЬ"', 'organizationsInn': ['3321020710'], 'organizationsName': ['ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "МОН\'ДЭЛИС РУСЬ"'], 'organizationsOgrn': ['1053300622407'], 'planId': None, 'prosecutorOrganization': None, 'prosecutorOrganizationId': None, 'publishedStatus': 'PUBLISHED', 'reasons': [301], 'reasonsList': [], 'recEmptyOrLate': False, 'regDateEgrul': None, 'regDateEgrulEn': None, 'regLate': False, 'regTypes': [], 'requirements': 0, 'requirementsList': [], 'resolved': False, 'resultEmpty': True, 'resultEmptyOrLate': False, 'resultInfoTypeCodes': [], 'resultViolationKnm': False, 'riskCategory': [], 'riskCategoryAndDangerClass': [], 'sezRegistryExists': False, 'signed': True, 'smevInfoType': None, 'smevMessageType': None, 'smevReceivedAt': None, 'smevReceivedAtEn': None, 'smevReceivedAtMonth': None, 'smevReceivedAtYear': None, 'spvRegistryExists': False, 'startDate': '11.01.2022', 'startDateEn': '2022-01-11', 'status': 'Предостережение объявлено', 'statusEgrul': '', 'statusId': 23, 'stopDate': '24.01.2022', 'stopDateEn': '2022-01-24', 'subjectTypeId': 0, 'supervisionType': 'Федеральный государственный санитарно-эпидемиологический контроль (надзор)', 'supervisionTypeId': 4, 'torRegistryExists': False, 'updatePlanDate': None, 'updatePlanDateLong': None, 'version': 'ERKNM', 'violationLawsuitTypeCodes': [], 'violationTypeCodes': [], 'year': 2022}
2023-01-24 18:09:17,417 - [INFO] - direct_sql.py - multiple_inserts(154) - Все проверки успешно занесены!
2023-01-24 18:17:02,588 - [INFO] - undetected_chromedriver.patcher - patch_exe(231) - patching driver executable C:\Users\zaitsev_ad\appdata\roaming\undetected_chromedriver\9dfd0f9268932fa9_chromedriver.exe
2023-01-24 18:17:05,359 - [INFO] - main_ERKNM - __init__(59) - Начало авторизации
2023-01-24 18:17:15,108 - [INFO] - main_ERKNM - autorize(161) - Autorization successfull completed!
2023-01-24 18:17:23,087 - [INFO] - ERKNM_http.py - get_all_pm_for_a_year(251) - сбор данных завершен, записываем для сохранения в json
2023-01-24 18:17:24,558 - [INFO] - ERKNM_http.py - get_all_pm_for_a_year(255) - Запись в json завершена, заносим в базу данных
2023-01-24 18:18:10,917 - [INFO] - undetected_chromedriver.patcher - patch_exe(231) - patching driver executable C:\Users\zaitsev_ad\appdata\roaming\undetected_chromedriver\fd6ce31c2cd8aac6_chromedriver.exe
2023-01-24 18:18:13,743 - [INFO] - main_ERKNM - __init__(59) - Начало авторизации
2023-01-24 18:18:23,921 - [INFO] - main_ERKNM - autorize(161) - Autorization successfull completed!
2023-01-24 18:18:32,111 - [INFO] - ERKNM_http.py - get_all_pm_for_a_year(251) - сбор данных завершен, записываем для сохранения в json
2023-01-24 18:18:33,527 - [INFO] - ERKNM_http.py - get_all_pm_for_a_year(255) - Запись в json завершена, заносим в базу данных
2023-01-24 18:18:33,740 - [INFO] - direct_sql.py - multiple_inserts(142) - старт программы
2023-01-24 18:18:42,540 - [ERROR] - sql.py - ultra_create_handler(223) - не получилось внести субъект (не рейд):
Traceback (most recent call last):
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\sql.py", line 214, in ultra_create_handler
    cursor.execute(f"""INSERT INTO knd_subject(name, address, inn, ogrn, e_mail, district) VALUES (
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\zaitsev_ad\PycharmProjects\ERKNM\venv\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'ДЭЛИС РУСЬ"\', \'601123, ОБЛАСТЬ, ВЛАДИМИРСКАЯ, РАЙ\' at line 2')
2023-01-24 18:18:42,549 - [INFO] - sql.py - ultra_create_handler(224) - {'actCreateDate': [], 'actCreateDateEn': [], 'addresses': ['601123, ОБЛАСТЬ, ВЛАДИМИРСКАЯ, РАЙОН, ПЕТУШИНСКИЙ, ГОРОД, ПОКРОВ, УЛИЦА, ФРАНЦА ШТОЛЬВЕРКА, ДОМ 10, 330120030000031'], 'admLevelId': 50001, 'appealed': False, 'approveDocOrderDate': None, 'approveDocOrderNum': None, 'approveDocRequestDate': None, 'approveDocRequestNum': None, 'approveDocs': [], 'approveRequired': False, 'approved': None, 'approvedErknm': None, 'chlistCount': 0, 'chlistFilledCount': 0, 'chlistFillingIndicationTypeId': [], 'collaboratingOrganizations': [], 'collaboratingOrganizationsIds': [], 'comment': None, 'controllingOrganization': 'Управление Роспотребнадзора по Владимирской области', 'controllingOrganizationId': 10001023037, 'createPlanDate': None, 'createPlanDateLong': None, 'createdByErpDb': False, 'createdById': 162319, 'dataNotEqualEGRUL': False, 'dataSetNotInTime': True, 'deleted': False, 'directDurationDays': None, 'disapprove': False, 'district': None, 'districtId': None, 'durationDays': None, 'durationHours': None, 'erknmActViolationIds': [], 'erknmResultKindDecisionIds': [], 'erpId': '33220041000101558820', 'events': [], 'federalLaw': '248', 'federalLawId': 3, 'fullFieldViolationKnm': False, 'hasViolations': False, 'id': 11630945, 'inn': '3321020710', 'inspectorFullName': ['Перова Татьяна Сергеевна'], 'isFromSmev': False, 'isHasApproveDocs': False, 'isHasCollaboratingOrganization': False, 'isHasRequirements': False, 'isHasViolationTerm': False, 'isPm': True, 'kind': 'Объявление предостережения', 'knmAnnulled': False, 'knmRejected': False, 'knmType': None, 'knmTypeId': None, 'legalBasisDocName': [], 'links': [], 'mspCategory': [], 'noPunishment': False, 'notifyLate': False, 'objectsKind': [], 'objectsSubKind': [], 'objectsType': [], 'ogrn': '1053300622407', 'oldKnm': None, 'oldPlan': None, 'orderDone': False, 'organizationName': 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "МОН\'ДЭЛИС РУСЬ"', 'organizationsInn': ['3321020710'], 'organizationsName': ['ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "МОН\'ДЭЛИС РУСЬ"'], 'organizationsOgrn': ['1053300622407'], 'planId': None, 'prosecutorOrganization': None, 'prosecutorOrganizationId': None, 'publishedStatus': 'PUBLISHED', 'reasons': [301], 'reasonsList': [], 'recEmptyOrLate': False, 'regDateEgrul': None, 'regDateEgrulEn': None, 'regLate': False, 'regTypes': [], 'requirements': 0, 'requirementsList': [], 'resolved': False, 'resultEmpty': True, 'resultEmptyOrLate': False, 'resultInfoTypeCodes': [], 'resultViolationKnm': False, 'riskCategory': [], 'riskCategoryAndDangerClass': [], 'sezRegistryExists': False, 'signed': True, 'smevInfoType': None, 'smevMessageType': None, 'smevReceivedAt': None, 'smevReceivedAtEn': None, 'smevReceivedAtMonth': None, 'smevReceivedAtYear': None, 'spvRegistryExists': False, 'startDate': '11.01.2022', 'startDateEn': '2022-01-11', 'status': 'Предостережение объявлено', 'statusEgrul': '', 'statusId': 23, 'stopDate': '24.01.2022', 'stopDateEn': '2022-01-24', 'subjectTypeId': 0, 'supervisionType': 'Федеральный государственный санитарно-эпидемиологический контроль (надзор)', 'supervisionTypeId': 4, 'torRegistryExists': False, 'updatePlanDate': None, 'updatePlanDateLong': None, 'version': 'ERKNM', 'violationLawsuitTypeCodes': [], 'violationTypeCodes': [], 'year': 2022}
2023-01-24 18:19:22,277 - [INFO] - direct_sql.py - multiple_inserts(154) - Все проверки успешно занесены!
